// Do NOT edit this file. It was automatically generated.
package ic

const (
	IC     = "release-2024-12-06_03-16-base" // https://github.com/dfinity/ic
	ICRC1  = "master"                        // https://github.com/dfinity/ICRC-1
	PORTAL = "master"                        // https://github.com/dfinity/portal
	SDK    = "0.24.3"                        // https://github.com/dfinity/sdk
)
